### ISSUE TITLE
API - DOES NOT SHOW IN LOG WHO COMPLETED THE ACTION ON THE API REQ

### ISSUE THREAD

**Issue by DJKieranl29** [yogurtsyum/qbot#149]
For example i have a promote command ingame, how can I log **who** did this command?

**Comment by yogurtsyum** [comment]
The API does not currently allow specifying who is responsible for an action. We'll keep this in mind as a future feature request, or you could modify the logAction line of api.ts yourself.

**Comment by DJKieranl29** [comment]
ok can you suggest the easiest way to add it?

**Comment by yogurtsyum** [comment]
Change the responsibleUser parameter to take from a URL query whenever logAction is ran.

**Comment by DJKieranl29** [comment]
That dont exist, do i gota make it?
![image](https://github.com/LengoLabs/qbot/assets/59117519/5639c272-d84d-4d0d-92a1-93a138d75cd1)

**Comment by yogurtsyum** [comment]
It's a placeholder parameter of **logAction**

**Comment by DJKieranl29** [comment]
right, so how do i get who sent the request anyways. would i have to add it to the body of the request? 
Also can you send me the info needed for "logaction" for example like: ```logaction(name,user,time)```?

**Comment by yogurtsyum** [comment]
`logAction` is defined in [src/handlers/handleLogging.ts](https://github.com/LengoLabs/qbot/blob/master/src/handlers/handleLogging.ts):

> ```async (action: string, moderator: DiscordUser | RobloxUser | GroupMember | any, reason?: string, target?: RobloxUser | PartialUser, rankChange?: string, endDate?: Date, body?: string, xpChange?: string)```

You're likely going to want to change the value currently set to "API Action."

**Comment by DJKieranl29** [comment]
I am at a stage where i have the user wh odid the action, but the user being effected im getting their username is "null" and i have no idea why...
code:


```lua
 app.post('/promote', async (req, res) => {
        const id  = req.body.id;
        const ActionByUser = req.body.By
        const ActionuserID = req.body.ByID
        if(!id || !ActionByUser || !ActionuserID) return res.send({ success: false, msg: 'Missing parameters.' });
        try {
            const robloxMember = await robloxGroup.getMember(Number(id));
            if(!robloxMember) throw new Error();
            const groupRoles = await robloxGroup.getRoles();
            const currentRoleIndex = groupRoles.findIndex((role) => role.rank === robloxMember.role.rank);
            const role = groupRoles[currentRoleIndex + 1];
            if(!role) throw new Error();
            await robloxGroup.updateMember(Number(id), role.id);
            console.log(robloxMember)
            console.log(robloxMember.name)
            logAction('Promote', `API Action (By: ` + ActionByUser + ` | ` + ActionuserID + `)`, robloxMember.name, robloxMember, `${robloxMember.role.name} (${robloxMember.role.rank}) → ${role.name} (${role.rank})`);
            return res.send({ success: true });
        } catch (err) {
            return res.send({ success: false, msg: 'Failed to rank.' });
        }
    });

```

**Comment by yogurtsyum** [comment]
I'd assume that's an issue with the code that sends the request, because it must be string "null" for !ActionByUser to return false, as it does here.

**Comment by DJKieranl29** [comment]
I think I have got a fix for it, just requires 2 extra api requirments: "SenderID" and "SenderUsername". And then now its working :)
