### ISSUE TITLE
error in help

### ISSUE THREAD

**Issue by cooperiscood** [yogurtsyum/qbot#29]
require('dotenv').config();
exports.run = async (client, message, args) => {
    return message.channel.send({embed: {
        color: 7948427,
        description: `**Here are my commands:**\n`
        + `\`${process.env.prefix}setrank <user> <rank name/number>\` - Ranks the user in the Roblox group to the specified rank number or name.\n`
        + `\`${process.env.prefix}promote <user>\` - Moves the user 1 rank up in the Roblox group.\n`
        + `\`${process.env.prefix}demote <user>\` - Moves the user 1 rank down in the Roblox group.\n`
        + `\`${process.env.prefix}fire <user>\` - Moves a user to the lowest rank possible besides Guest.\n`
        + `\`${process.env.prefix}shout <message>\` - Posts a group shout.\n`
        + `\`${process.env.prefix}clearshout\` - Clears the group shout.\n`
        + `\`${process.env.prefix}currentshout\` - Shows the current group shout.\n`
            name: message.author.tag,
            icon_url: message.author.displayAvatarURL()
        }
    }});
}
``

**Comment by IeuanGol** [comment]
What is the error?

**Comment by Clu3l3s3** [comment]
Please put the error & code in https://gist.github.com

1. Code
2. Error

**Comment by IeuanGol** [comment]
> Please put the error & code in https://gist.github.com
> 
> 1. Code
> 2. Error
> 
> 

Sending it on here is fine it just needs to be provided within a code block.

**Comment by yogurtsyum** [comment]
1) The first part of the description is not wrapped inside a string.
2) The `name` and `icon_url` values go inside an `author` or `footer` object.
3) Missing a comma after the description.

**Comment by cooperiscood** [comment]
OK.

**Comment by IeuanGol** [comment]
Please refer to what Lengo has already mentioned.

**Comment by IeuanGol** [comment]
If this is solved, please close the issue.
