### ISSUE TITLE
demote command not working even when bot is at Highest rank

### ISSUE THREAD

**Issue by ActuallyKrypto** [yogurtsyum/qbot#31]
When I tried to demote a person of lower rank, the command didn't work

**Comment by frostgit-dev** [comment]
Code please.

**Comment by frostgit-dev** [comment]
And the error.

**Comment by ActuallyKrypto** [comment]
![qbot](https://user-images.githubusercontent.com/70694802/92101875-6416a000-edfb-11ea-9764-38ee0746257b.PNG)

**Comment by Clu3l3s3** [comment]
1. Make sure that you ranked the right account in the group.

2. Make sure the rank your bot has in the group has ranking permissions,

3. Make sure your got is high enough in the ranks to be able to promote that user.

**Comment by TypicallyShad** [comment]
> 1. Make sure that you ranked the right account in the group.
> 2. Make sure the rank your bot has in the group has ranking permissions,
> 3. Make sure your bot is high enough in the ranks to be able to promote that user.

@Clu3l3s3, please don't provide support if you don't know the errors thrown by qbot.

**Comment by TypicallyShad** [comment]
@ActuallyKrypto 

The issue you're facing is caused because of the maximumRank setting in your env file, also known as your configuration file for qbot.

You may have set an incorrect number, if so, you can simply change it. If this issue is fixed, please close this.

**Comment by ActuallyKrypto** [comment]
Okay thanks! It works now, I thought that was minimum rank.
