### ISSUE TITLE
Not an issue, but a question.

### ISSUE THREAD

**Issue by malachy09** [yogurtsyum/qbot#32]
Hi there!

I was just wondering how to make it so the bot can respond to webhooks? I have a webhook that responds to requests for ranking, but it won't rank when it sends in a request. It doesn't return an error or anything, it's almost like it ignores it.

Is there a way I can configure the bot so it can respond to webhook ranking? Thanks!
![image](https://user-images.githubusercontent.com/70695407/92102368-6d414600-edd6-11ea-8341-c2a4a82b85a6.png)

**Comment by Clu3l3s3** [comment]
There probably is a way, but that would be very unsecure as someone can get your webhook and promote themselves. I would recommend not doing it.

**Comment by malachy09** [comment]
I understand that definitely, however the webhook is safely secure and no one else can access it apart from me. Would you happen to know how to do this?

**Comment by Clu3l3s3** [comment]
I don't know how to, but their is most likely a way. Wait & see if someone else comes and answers.

**Comment by malachy09** [comment]
Alrighty, no worries! Thank you!
