### ISSUE TITLE
Does anyone know how to make a group rank bot for roblox?

### ISSUE THREAD

**Issue by achocolatemilk** [yogurtsyum/qbot#34]

**Comment by yogurtsyum** [comment]
Can you be a bit more specific? Are you talking about ranking people from inside a Roblox game? If so, you can use my other open source project, [In Game Ranking](https://github.com/yogurtsyum/in-game-ranking).

**Comment by yogurtsyum** [comment]
This ticket has been closed for inactivity. Please re-open it if you still need help.
