### ISSUE TITLE
qbot issue

### ISSUE THREAD

**Issue by chrisrbxm** [yogurtsyum/qbot#35]
my bot says that the user is not in group, and the "fire" command does not trigger an embed or anything

**Comment by yogurtsyum** [comment]
For the first question, that likely means the user is not in the group id specified in the config file.

For the second question, any errors?

**Comment by chrisrbxm** [comment]
no it shows no errors in the console

**Comment by yogurtsyum** [comment]
Then there's likely no `commands/fire.js` file

**Comment by chrisrbxm** [comment]
im in the fire.js file rn

**Comment by yogurtsyum** [comment]
well if there's no error and no reply then its probably not being ran

**Comment by chrisrbxm** [comment]
im running it, but all the other commands responses work

**Comment by yogurtsyum** [comment]
Then I'm just gonna assume you're not noticing the error.

**Comment by yogurtsyum** [comment]
Can you send a picture of logs?

**Comment by chrisrbxm** [comment]
sure

**Comment by chrisrbxm** [comment]
![image](https://user-images.githubusercontent.com/69480804/92283161-4d407e00-eecd-11ea-8e51-87ac1d86029a.png)

**Comment by TheShadowGamer** [comment]
Can you scroll a bit higher in the logs and send a screen shot of that?

**Comment by chrisrbxm** [comment]
![image](https://user-images.githubusercontent.com/69480804/92283430-da83d280-eecd-11ea-9462-567a66390fe6.png)

**Comment by TheShadowGamer** [comment]
Can you send a picture of everything?

**Comment by chrisrbxm** [comment]
![image](https://user-images.githubusercontent.com/69480804/92283966-12d7e080-eecf-11ea-8b22-c13543508c95.png)
![image](https://user-images.githubusercontent.com/69480804/92283975-179c9480-eecf-11ea-8aef-2a5c697be199.png)
![image](https://user-images.githubusercontent.com/69480804/92283994-1d927580-eecf-11ea-8362-8426f9f6a059.png)

**Comment by chrisrbxm** [comment]
![image](https://user-images.githubusercontent.com/69480804/92284431-f38d8300-eecf-11ea-9551-adc57d833601.png)

**Comment by TheShadowGamer** [comment]
What happens if you try now?

**Comment by chrisrbxm** [comment]
same problems as stated above

**Comment by yogurtsyum** [comment]
that picture isn't logs thats the shell. logs are often above the shell

**Comment by yogurtsyum** [comment]
This ticket has been closed for inactivity. Please re-open it if you still need help.
