### ISSUE TITLE
qbot & roblox bot account protection & private projects

### ISSUE THREAD

**Issue by msami789** [yogurtsyum/qbot#38]
Yesterday someone hacked into my bot account for qbot to operate and raided my group. I need to know if I can set these precautions without the ranking system breaking:

- Set Two Factor Authentication on the Roblox Bot Account
- Set my repl.it to private project (I have pro or whatever it's called lol)

Thanks. 👍

**Comment by yogurtsyum** [comment]
Hello,
What are you using to host your bot and have you ever sent your bot token or cookie anywhere?

**Comment by yogurtsyum** [comment]
Because this is nearly impossible unless the bot token or cookie (or password) was somehow publicized somewhere.

**Comment by IeuanGol** [comment]
Are you sure they had access via qBot?

This could been that the user has the `Ranking Permission` role. 

If this isn't the case perhaps your credentials were exposed..

I recommend if you're going to pay for something I'd buy a VPS, [Digital Ocean](https://www.digitalocean.com/) you can buy a single server for $5/month.

**Comment by yogurtsyum** [comment]
My guess is the issue is not with the credentials being exposed or someone having the role.

My guess is that they have it so “Public Bot” is enabled and anyone can invite the bot.

**Comment by msami789** [comment]
@yogurtsyum @IeuanGol 
I'm not saying this was done via hacking qbot, but I wanted to know mainly if I can set two factor authentication and the system will still be able to log in via cookie.

> My guess is that they have it so “Public Bot” is enabled and anyone can invite the bot.

Ahah! You might be right, I forgot to turn off public invites. That must be how because there was no log of someone using the ranking bot nor was there log of the message that it ranked being deleted

**Comment by IeuanGol** [comment]
2FA shouldn't make a difference since it is done via cookie.

**Comment by msami789** [comment]
And look what I found;
![Screen Shot 2020-09-06 at 11 31 27 AM](https://user-images.githubusercontent.com/52465795/92329293-9a8b2f80-f034-11ea-8807-cb41b1e56978.png)
Looks like someone found out the bot token.

Will change the token and turn off public

**Comment by IeuanGol** [comment]
Bots can only be added via a client is which is publicly available information.

**Comment by yogurtsyum** [comment]
You don't need the bot token to add it to a server, just the Client ID, which is pretty much public information.

Be sure to make sure the bot leaves that extra server it's in.
