### ISSUE TITLE
custom command/system

### ISSUE THREAD

**Issue by msami789** [yogurtsyum/qbot#40]
I know this isn’t specific to qbot but for those who don’t know, my bot was on public invite and my group got raided as the bot is in another server.

Does anyone know how I could run a command, (maybe an eval?) to figure out the members of the other server or even get an invite to it.

Thanks.

**Comment by yogurtsyum** [comment]
Getting the members of another server seems like an invasion of privacy. But, you could just leave it with code like this:
```js
async function leaveGuild(){
    let guild = await client.guilds.fetch('GUILD ID');
    guild.leave();
}
leaveGuild();
```
That could be ran through eval or put in a ready event.

**Comment by msami789** [comment]
> Getting the members of another server or getting an invite to it seems like an invasion of privacy. But, you could just leave it with code like this:
> 
> ```js
> async function leaveGuild(){
>     let guild = await client.guilds.fetch('GUILD ID');
>     guild.leave();
> }
> leaveGuild();
> ```
> 
> That could be ran through eval or put in a ready event.

How can I add an eval, can’t seem to find the custom commands list?

**Comment by IeuanGol** [comment]
https://github.com/yogurtsyum/qbot-plugins/blob/master/directory.md#eval-command

**Comment by msami789** [comment]
do I have to put the guild id that the bot should leave in “GUILD ID” because I dont have it

**Comment by IeuanGol** [comment]
```js
client.guilds.cache.map(g => g.id)
```

**Comment by msami789** [comment]
it says that the code complied, where do i find the result?

**Comment by IeuanGol** [comment]
Restart the bot and see how many servers it's in.

**Comment by yogurtsyum** [comment]
You could console.log that code that Ieuan provided.

**Comment by IeuanGol** [comment]
Sorry about that I wasn't thinking properly 😅

**Comment by IeuanGol** [comment]
Did you manage to solve this?

**Comment by zachariapopcorn** [comment]
Just do this
```js
client.on('ready', async() => {
     let guilds = client.guilds.cache.array();
     for(var i = 0; i < guilds.length; i++) {
          if(guilds[i].id !== "GUILD ID HERE") {
               guild[i].leave();
          }
     }
});
```

**Comment by IeuanGol** [comment]
Please could you close this issue if you've solved it now.
