### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tomluwis116** [yogurtsyum/qbot#42]
Oops! An unexpected error has occured. It has been logged to the bot console.

**Comment by Tomluwis116** [comment]
What does that even mean?

**Comment by IeuanGol** [comment]
Check the server error logs.

**Comment by Tomluwis116** [comment]
I did

**Comment by Tomluwis116** [comment]
@IeuanGol Can you tell me what to do to get the bot working

**Comment by IeuanGol** [comment]
Provide the error shown in the console.

**Comment by Tomluwis116** [comment]
> 

> [
![image](https://user-images.githubusercontent.com/69173705/92538642-d4129500-f204-11ea-9008-3e7a287675de.png)
](url)

**Comment by emergingdarkness** [comment]
You aren’ t logged into the roblox bot account, make sure you use a incognito tab

**Comment by yogurtsyum** [comment]
Please get a new cookie for your bot and this time don't log out after getting it, as this resets it. You can use an incognito window so you can still access the site without being on the bot account on a regular window after getting the cookie.

**Comment by Tomluwis116** [comment]
@emergingdarkness @IeuanGol Thank you guys I got it to work now
