### ISSUE TITLE
Cookie error possibly?

### ISSUE THREAD

**Issue by Cytronyx** [yogurtsyum/qbot#43]
Using the bots cookie, everything is working as it should except when you run any command it just keeps stating "You need the Ranking Permissions or Shout Permissions role to run this command." the bot account has all role permissions in the group already. Any help would be highly appreciated.

**Comment by shalllowhacker100** [comment]
You need to make a discord role called Ranking Permission and it should work

**Comment by IeuanGol** [comment]
> You need to make a discord role called Ranking Permission and it should work

and give it to anyone who you want to use commands (including yourself)

**Comment by shalllowhacker100** [comment]
Yup What leuanGol Said

**Comment by yogurtsyum** [comment]
It's called `Ranking Permissions` not `Ranking Permission`.

**Comment by holidaygamers** [comment]
You're able to essentially make it any role if you rename the Ranking Permission to something else.

**Comment by IeuanGol** [comment]
> You're able to essentially make it any role if you rename the Ranking Permission to something else.

We are proving help based on the error message once again the role name is `Ranking Permissions` ~~not Ranking Pernission~~

**Comment by IeuanGol** [comment]
Did you manage to solve this?

**Comment by imannyz** [comment]
Indeed I have, it was lack of creating a role in the Discord server called Ranking Permission etc, maybe make that clearer in the documentation for new users :) because I thought it was to do with group role permissions.

**Comment by IeuanGol** [comment]
Alright could you close this issue please.

**Comment by IeuanGol** [comment]
Please could you close this issue if you've solved it now.
