### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xxjohneyxx11** [yogurtsyum/qbot#44]
I want a ;kick command for Qbot, and when I run ;kick it will kick them from the Game.

**Comment by IeuanGol** [comment]
We do not spoon feed code, sorry.

**Comment by frostgit-dev** [comment]
Qbot is a discord bot. If you want to kick, use BA Essentials.

**Comment by zachariapopcorn** [comment]
There's something called plugins, @frostgit-dev. What I would do to make this is to make some sort of webserver (qbot has this built in) and then every few seconds, Roblox pings that webserver to see if there's a kick request, if there is, it kicks that player, if there's not, then it does nothing

**Comment by IeuanGol** [comment]
Please could you close this issue if you've solved it now.

**Comment by ObbyMasterMine** [comment]
There is one that also uses repl.it, you make you own bot though. It's not under qBot or endorsed by qBot in anyway, but it will work for the Discord to Roblox Moderation. Here it is. 

https://devforum.roblox.com/t/pegasus-v1-1-discord-firebase-roblox-ban-bot/753801

If you found this helpful and do not need anymore support, please close this issue if its solved.

If you need to contact support again, you can join our server, [here](discord.gg/j47m7t4) or make a new issue.


Have a good day!

**Comment by emergingdarkness** [comment]
You just sent a link to a random github repository..

**Comment by ObbyMasterMine** [comment]
Oopsy, I fixed it.

**Comment by IeuanGol** [comment]
Please close the issue in that case
