### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by K00L1000** [yogurtsyum/qbot#47]
Hello! A few weeks ago I asked if everyone could be dm'ed in a guild and for obvious reasons no due to rate limiting and abuse. In a server I saw https://gyazo.com/2e966bf1964ecfd4ce1220daea250d1a and the bot dm'ed https://gyazo.com/2e966bf1964ecfd4ce1220daea250d1a. How is this possible there are 200 people in the server.

**Comment by IeuanGol** [comment]
Mass messaging members is against the TOS.. We shall not provide support with the question asked.

FYI: From the beginning of next month it will be impossible for bots to download all of the members within a Discord server. Thus disabling the ability to mass message.

**Comment by IeuanGol** [comment]
Please could you close this issue if you've solved it now.

**Comment by zachariapopcorn** [comment]
I mean, all you need to do is fetch all the guild members and put them in an array. Then, you need to for-loop through that array, only problem would be rate limits
