### ISSUE TITLE
How do I add plugins?

### ISSUE THREAD

**Issue by xxjohneyxx11** [yogurtsyum/qbot#48]

**Comment by IeuanGol** [comment]
Check the read me of the repo

https://github.com/yogurtsyum/qbot-plugins

**Comment by xxjohneyxx11** [comment]
Also, I want to add my Plugin commands to my help command, how do I do that?

**Comment by IeuanGol** [comment]
Edit the help command

**Comment by xxjohneyxx11** [comment]
I did, but then the Bot would not respond to ;help.

**Comment by IeuanGol** [comment]
Check your errors, most likely syntax error.

**Comment by xxjohneyxx11** [comment]
Alright.

**Comment by xxjohneyxx11** [comment]
Can you also check out my Other Question?

**Comment by IeuanGol** [comment]
#50

**Comment by IeuanGol** [comment]
If this is solved please close it.

**Comment by xxjohneyxx11** [comment]
Okay.
