### ISSUE TITLE
How do I use Trello API with Qbot, plus is it Possible?

### ISSUE THREAD

**Issue by xxjohneyxx11** [yogurtsyum/qbot#50]

**Comment by IeuanGol** [comment]
If you code it yourself it's technically possible..

However it's not supported, so no.

**Comment by xxjohneyxx11** [comment]
Alright, I don't know how to code it, but do you know how I can learn how to use Discord API and Trello API?

**Comment by IeuanGol** [comment]
Do you already have a good knowledge of JavaScript?

**Comment by xxjohneyxx11** [comment]
No, I just learned how to make Qbot by a Friend.

**Comment by IeuanGol** [comment]
A good knowledge of JS is required first.

**Comment by xxjohneyxx11** [comment]
Okay, I can learn..

**Comment by zachariapopcorn** [comment]
It's possible alright, we have the tools available

**Comment by xxjohneyxx11** [comment]
Okay, thanks.

**Comment by xxjohneyxx11** [comment]
Why is this Happening? 
;deny-join <user> - Denies a user's join request.;membercount Shows all of the Current Members`;getinfo <username> Get's the Users ID, and username

**Comment by xxjohneyxx11** [comment]
`  + `\`${process.env.prefix}deny-join <user>\` - Denies a user's join request.`
        
        + `\`${process.env.prefix}membercount Shows all of the Current Members`
        
        + `\`${process.env.prefix}getinfo <username> Get's the Users ID, and username.`,
        
        author: {
            name: message.author.tag,
            icon_url: message.author.displayAvatarURL()
        }
    }});
}`

**Comment by xxjohneyxx11** [comment]
@IeuanGol

**Comment by TypicallyShad** [comment]
Use \n for new lines,

**Comment by xxjohneyxx11** [comment]
What's wrong with this line?
[+ `\`${process.env.prefix}membercount Shows all of the Current Members.
    
        + `\`${process.env.prefix}getinfo <username> Get's the Users ID, and username.`,
        ](

**Comment by IeuanGol** [comment]
> Use \n for new lines,

**Comment by xxjohneyxx11** [comment]
I did, it says this: ;deny-join <user> - Denies a user's join request. /n

**Comment by xxjohneyxx11** [comment]
Also, why does my bot not respond to this?
`equire('dotenv').config();
exports.run = async (client, message, args) => {
    return message.channel.send({embed: {
        color: 7948427,
        description: `**Here are my commands:**\n`
        + `\`${process.env.prefix}help\` - Shows this list of commands.\n`
        + `\`${process.env.prefix}setrank <user> <rank name/number>\` - Ranks the user in the Roblox group to the specified rank number or name.\n`
        + `\`${process.env.prefix}promote <user>\` - Moves the user 1 rank up in the Roblox group.\n`
        + `\`${process.env.prefix}demote <user>\` - Moves the user 1 rank down in the Roblox group.\n`
        + `\`${process.env.prefix}fire <user>\` - Moves a user to the lowest rank possible besides Guest.\n`
        + `\`${process.env.prefix}shout <message>\` - Posts a group shout.\n`
        + `\`${process.env.prefix}clearshout\` - Clears the group shout.\n`
        + `\`${process.env.prefix}currentshout\` - Shows the current group shout.\n`
        + `\`${process.env.prefix}accept-join <user>\` - Accepts a user's join request.\n`
 + `\`${process.env.prefix}membercount Shows all of the Current members, it's the same as Serverinfo.\n`
         + `\`${process.env.prefix}getinfo Get's the Users ID, and username.\n`
+ `\`${process.env.prefix}deny-join <user>\` - Denies a user's join request.`,
        author: {
            name: message.author.tag,
            icon_url: message.author.displayAvatarURL()
        }
    }});`

**Comment by xxjohneyxx11** [comment]
equire('dotenv').config();
exports.run = async (client, message, args) => {
    return message.channel.send({embed: {
        color: 7948427,
        description: `**Here are my commands:**\n`
        + `\`${process.env.prefix}help\` - Shows this list of commands.\n`
        + `\`${process.env.prefix}setrank <user> <rank name/number>\` - Ranks the user in the Roblox group to the specified rank number or name.\n`
        + `\`${process.env.prefix}promote <user>\` - Moves the user 1 rank up in the Roblox group.\n`
        + `\`${process.env.prefix}demote <user>\` - Moves the user 1 rank down in the Roblox group.\n`
        + `\`${process.env.prefix}fire <user>\` - Moves a user to the lowest rank possible besides Guest.\n`
        + `\`${process.env.prefix}shout <message>\` - Posts a group shout.\n`
        + `\`${process.env.prefix}clearshout\` - Clears the group shout.\n`
        + `\`${process.env.prefix}currentshout\` - Shows the current group shout.\n`
        + `\`${process.env.prefix}accept-join <user>\` - Accepts a user's join request.\n`
 + `\`${process.env.prefix}membercount Shows all of the Current members, it's the same as Serverinfo.\n`
         + `\`${process.env.prefix}getinfo Get's the Users ID, and username.\n`
+ `\`${process.env.prefix}deny-join <user>\` - Denies a user's join request.`,
        author: {
            name: message.author.tag,
            icon_url: message.author.displayAvatarURL()
        }
    }});

**Comment by xxjohneyxx11** [comment]
@IeuanGol

**Comment by xxjohneyxx11** [comment]
@TypicallyShad Can you help?

**Comment by xxjohneyxx11** [comment]
Hello?

**Comment by IeuanGol** [comment]
What's the issue?

**Comment by IeuanGol** [comment]
Please could you close this issue if you've solved it now.
