### ISSUE TITLE
Suggestion - Guild Ban Method

### ISSUE THREAD

**Issue by zachariapopcorn** [yogurtsyum/qbot#51]
Suggestion: Make a variable called allowed guilds which would be an empty array. Then have the user put their guild id in the array, then for every message or when the bot boots, check every guild id that the bot has access to and if it doesn't equal the guild id(s) in the array, it leaves the guilds.
How would this be helpful: This would be helpful for people for forget to private their bot

**Comment by IeuanGol** [comment]
The has now reopened could you post it in #suggestions, please.

**Comment by zachariapopcorn** [comment]
Alright
