### ISSUE TITLE
cookie wont work

### ISSUE THREAD

**Issue by gdfggfgf** [yogurtsyum/qbot#52]

**Comment by TheShadowGamer** [comment]
Are you signing out of the account?

**Comment by gdfggfgf** [comment]
yes

**Comment by TheShadowGamer** [comment]
That’s the problem

**Comment by IeuanGol** [comment]
Via the sign out button?

**Comment by TheShadowGamer** [comment]
Sign in on an incognito window and just close the Window when you get the cookie

**Comment by gdfggfgf** [comment]
this what it says Failed to validate cookie: Are you sure the cookie is valid?
Ensure you include the full cookie, including warning text.
Issue with logging in: Error: Error: You are not logged in

**Comment by gdfggfgf** [comment]
should i get kicked out of the account?

**Comment by gdfggfgf** [comment]
wait do i have to stay on the account

**Comment by TheShadowGamer** [comment]
Getting signed out is normal.

**Comment by TheShadowGamer** [comment]
You just don’t want to sign out manually

**Comment by IeuanGol** [comment]
Please could you close this issue if you've solved it now.
