### ISSUE TITLE
Command handler having issues

### ISSUE THREAD

**Issue by K00L1000** [yogurtsyum/qbot#54]
https://media.discordapp.net/attachments/731392965360091196/755416383138824282/unknown.png?width=1442&height=128 

Why do I keep getting this error?

**Comment by Clu3l3s3** [comment]
Please update the link as it it showing invalid.

**Comment by IeuanGol** [comment]
Getting a 403 on this, please either provide another image ([imgur](https://imgur.com/)) might be more helpful. 

Or please close this issue if you've solved it now.

**Comment by zachariapopcorn** [comment]
You won't get an error unless it can't access the commands folder, which shouldn't be an issue unless you modified something
