### ISSUE TITLE
X-CSRF-TOKEN

### ISSUE THREAD

**Issue by R9UBEN** [yogurtsyum/qbot#55]
When I attempt to rank someone, I get an error.

`An error occured when running the promote command: Error: Did not receive X-CSRF-TOKEN`

![image](https://user-images.githubusercontent.com/69516737/93381373-77dcf000-f858-11ea-8f66-dd25271d3c8f.png)

**Comment by IeuanGol** [comment]
Update noblox

**Comment by R9UBEN** [comment]
How do I do that?

**Comment by emergingdarkness** [comment]
npm i noblox.js

**Comment by IeuanGol** [comment]
Please could you close this issue if you've solved it now.
