### ISSUE TITLE
Group Shout

### ISSUE THREAD

**Issue by mark181933** [yogurtsyum/qbot#58]
So the bot use to post a shout in a channel when a shout goes out but now it wont. Note(s): the bot is super slow and always breaks

**Comment by yogurtsyum** [comment]
Any errors in the bot logs?

**Comment by mark181933** [comment]
@yogurtsyum nope

**Comment by yogurtsyum** [comment]
If there's no errors, it never detected a shout. So you probably have the wrong group id or the shout text was the same as before.

**Comment by mark181933** [comment]
@yogurtsyum i will go over that and try again

**Comment by mark181933** [comment]
@yogurtsyum so everything is right with the id and the shout. any other ideas on why it wont work?

**Comment by yogurtsyum** [comment]
Can you send a picture of the bot logs?

**Comment by mark181933** [comment]
what do you mean by bot logs @yogurtsyum

**Comment by yogurtsyum** [comment]
The logs for the bot. And can you please stop pinging me in every single reply?

**Comment by mark181933** [comment]
ok so it works randomly now

**Comment by yogurtsyum** [comment]
Then maybe you didn't wait the 30 seconds it takes to log.

**Comment by mark181933** [comment]
well i did then i just made a new channel and it worked
