### ISSUE TITLE
The bot won't send any messages

### ISSUE THREAD

**Issue by GlibD** [yogurtsyum/qbot#60]
It doesn't show anything wrong on Repl.it or UptimeRobot, the bot role has the administrator permission, and yet the bot won't send any messages. It had been working fine for almost a month and today it just stopped, even though it still ranks people in the group, it won't log them or answer to the commands.

**Comment by emergingdarkness** [comment]
Did you edit your command? Does it have permission. Its a repl down time probably, Which commands have this issue?

**Comment by GlibD** [comment]
> 
> 
> Did you edit your command? Its a repl down time probably, Which commands have this issue?

I didn't change anything. As far as I've tested, none of the commands are "working" (demote, promote, help...) even though they're still ranking people in the group, just not sending the logs to the proper channel or answering to the commands. I'll wait for some time and see if it's really a Repl down time.

**Comment by GlibD** [comment]
The issue has been fixed, it was most likely a downtime as you said. Thank you for the support!
