### ISSUE TITLE
Help, can someone make me a security script, my bot was hacked.

### ISSUE THREAD

**Issue by bmvarrato** [yogurtsyum/qbot#62]
HELP

**Comment by Kf637** [comment]
What did you use? Did you use glitch?

**Comment by yogurtsyum** [comment]
What do you expect a "security script" to do?
The bot is secure if you don't leak the token and have Public Bot disabled.

**Comment by Kf637** [comment]
You need to make sure that your project is private if you used [glitch](https://glitch.com/)

**Comment by yogurtsyum** [comment]
The qbot setup instructions use repl.it anyways.

**Comment by bmvarrato** [comment]
No, I did not use glitch. And it is private.

**Comment by bmvarrato** [comment]
I also did not leak the token.

**Comment by NodeWired** [comment]
What are you using to host it?

**Comment by bmvarrato** [comment]
UptimeRobot

**Comment by NodeWired** [comment]
Uptime robot is not a host

**Comment by NodeWired** [comment]
Uptime robot is a pinging site, on the setup page what have u got as the url glitch.com or repl.it?

**Comment by bmvarrato** [comment]
repl.it

**Comment by NodeWired** [comment]
then theres ur problem, someone most likely guessed ur project and then access the bot token etc

**Comment by NodeWired** [comment]
maybe invest in a vps?

**Comment by yogurtsyum** [comment]
Configuration values are stored in .env which is kept private on repl.it, so please don’t provide inaccurate information @NodeWired. The issue is likely the bot being set as public in the Discord Developer Portal.

**Comment by yogurtsyum** [comment]
@bmvarrato Can you send a screenshot of the Public Bot setting in the Bot tab of your application in the Discord Developer Portal?

**Comment by bmvarrato** [comment]
![unknown](https://user-images.githubusercontent.com/70340552/94463954-bd1fec80-018b-11eb-9fd5-17443a951092.png)

There, also the .env file is called .env. How do I apply as customer support? I have some coding knowloge.

**Comment by yogurtsyum** [comment]
Then is it possible the .env file is in a folder or you gave someone else access to the token? Or maybe put the token on Github?

To be Staff in the support server you need to provide support and if you’re providing active and accurate support for some time you might be offered an invite to the Staff team.
