### ISSUE TITLE
Audit Logs

### ISSUE THREAD

**Issue by aipic** [yogurtsyum/qbot#66]
Bot won't display audit logs. Cookies are correct since promotions and demotions work. Bot has access to all permissions.

**Comment by IeuanGol** [comment]
For some reason, noblox.js might log InternalServerError or Insufficient permissions to complete the request. after using the audit log integration for some time. @yogurtsyum will look into a good solution to get around this in the future, but in the mean time your bot should still work.

**Comment by aipic** [comment]
The bot works and perfectly. Thank you for the response, I would also wish that a few of the plugins in the past version could be transferred onto this one.

**Comment by IeuanGol** [comment]
That is planned! In our [Discord server](https://discord.gg/976dpbB) you can check the status about this

**Comment by yogurtsyum** [comment]
If you need anything else, feel free to re-open this ticket.
