### ISSUE TITLE
New storage system might have problems with repl.it

### ISSUE THREAD

**Issue by Lebyy** [yogurtsyum/qbot#75]
Hello! The new SQLite storage system might have problems storing data on replit, Read more [here](https://github.com/AnIdiotsGuide/discordjs-bot-guide/issues/119#issuecomment-691539040).
I highly recommend you to use the replit database or mongodb. 
Some easy wrappers for them are :-
[Quick.Replit](https://www.npmjs.com/package/quick.replit).
[QuickMongo](https://www.npmjs.com/package/quickmongo).

**Comment by yogurtsyum** [comment]
Hey Lebyy,

We're aware that the storage system will probably not work on Repl.it. The issue with using their built in database is that then it won't work at all on a VPS, and using MongoDB would make the setup guide way more complicated. So at least for now, our only option is just noting that the XP system might reset when hosted on Repl.it.

Thanks for creating an issue.

**Comment by yogurtsyum** [comment]
Hey Lebyy,

We're aware that the storage system will probably not work on Repl.it. The issue with using their built in database is that then it won't work at all on a VPS, and using MongoDB would make the setup guide way more complicated. I'll bring this up with the staff team though and see if we could write a simple guide for setting up MongoDB though.

Thanks for creating an issue.

**Comment by Lebyy** [comment]
Alright 👍
