### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by Tomluwis116** [yogurtsyum/qbot#76]
Hey I was making a bot for my friend and every time I click on run it just says your app is currently listening to port 3000

**Comment by yogurtsyum** [comment]
Hi, is there any other errors?

Also, I recommend you use the [support server](https://lengolabs.com/discord) for quicker support.

**Comment by Tomluwis116** [comment]
Yeah it says there's an error
![image](https://user-images.githubusercontent.com/69173705/122329115-72e7c280-cef6-11eb-821f-b44b608aeda6.png)

**Comment by Tomluwis116** [comment]
Okay nevermind I got the bot to work now
